
### POST /transactions

POST http://localhost:8080/transaction
Content-Type: application/json

{
    "amount": 100,
    "paymentMethod": "PIX",
    "currencyCode": "BRL",
    "description": "Compra de teste"
}

### GET /transactions

GET http://localhost:8080/transactions

### GET /transactions/:id

GET http://localhost:8080/transaction/b43f6fb8-a92d-4cce-9aa5-42d5e05dd191
