
### POST /transactions

POST http://localhost:8080/transaction
Content-Type: application/json

{
    "amount": 100,
    "paymentMethod": "PIX",
    "currencyCode": "BRL",
    "description": "Compra de teste"
}

### GET /transactions

GET http://localhost:8080/transactions

### GET /transactions/:id

GET http://localhost:8080/transaction/085742f4-b358-421c-a924-cbbe7fcd32fb
